// Static phone codes served as an API route.
// Loaded lazily by AppPhoneInput only when the dropdown is opened.
export default defineEventHandler(() => [
  { name: 'Malaysia',          code: 'MY', emoji: '🇲🇾', dialCode: '+60',  mask: '##-####-####'   },
  { name: 'Singapore',         code: 'SG', emoji: '🇸🇬', dialCode: '+65',  mask: '####-####'      },
  { name: 'Indonesia',         code: 'ID', emoji: '🇮🇩', dialCode: '+62',  mask: '###-####-####'  },
  { name: 'Thailand',          code: 'TH', emoji: '🇹🇭', dialCode: '+66',  mask: '##-####-####'   },
  { name: 'Philippines',       code: 'PH', emoji: '🇵🇭', dialCode: '+63',  mask: '###-###-####'   },
  { name: 'Vietnam',           code: 'VN', emoji: '🇻🇳', dialCode: '+84',  mask: '##-####-###'    },
  { name: 'Brunei',            code: 'BN', emoji: '🇧🇳', dialCode: '+673', mask: '###-####'       },
  { name: 'Myanmar',           code: 'MM', emoji: '🇲🇲', dialCode: '+95',  mask: '##-###-####'    },
  { name: 'Cambodia',          code: 'KH', emoji: '🇰🇭', dialCode: '+855', mask: '##-###-###'     },
  { name: 'Australia',         code: 'AU', emoji: '🇦🇺', dialCode: '+61',  mask: '###-###-###'    },
  { name: 'New Zealand',       code: 'NZ', emoji: '🇳🇿', dialCode: '+64',  mask: '##-###-####'    },
  { name: 'India',             code: 'IN', emoji: '🇮🇳', dialCode: '+91',  mask: '#####-#####'    },
  { name: 'China',             code: 'CN', emoji: '🇨🇳', dialCode: '+86',  mask: '###-####-####'  },
  { name: 'Japan',             code: 'JP', emoji: '🇯🇵', dialCode: '+81',  mask: '##-####-####'   },
  { name: 'South Korea',       code: 'KR', emoji: '🇰🇷', dialCode: '+82',  mask: '##-####-####'   },
  { name: 'Hong Kong',         code: 'HK', emoji: '🇭🇰', dialCode: '+852', mask: '####-####'      },
  { name: 'Taiwan',            code: 'TW', emoji: '🇹🇼', dialCode: '+886', mask: '###-###-###'    },
  { name: 'United Arab Emirates', code: 'AE', emoji: '🇦🇪', dialCode: '+971', mask: '##-###-####' },
  { name: 'Saudi Arabia',      code: 'SA', emoji: '🇸🇦', dialCode: '+966', mask: '##-###-####'    },
  { name: 'United Kingdom',    code: 'GB', emoji: '🇬🇧', dialCode: '+44',  mask: '####-######'    },
  { name: 'United States',     code: 'US', emoji: '🇺🇸', dialCode: '+1',   mask: '(###) ###-####' },
  { name: 'Canada',            code: 'CA', emoji: '🇨🇦', dialCode: '+1',   mask: '(###) ###-####' },
  { name: 'Germany',           code: 'DE', emoji: '🇩🇪', dialCode: '+49',  mask: '####-########'  },
  { name: 'France',            code: 'FR', emoji: '🇫🇷', dialCode: '+33',  mask: '##-##-##-##-##' },
  { name: 'Netherlands',       code: 'NL', emoji: '🇳🇱', dialCode: '+31',  mask: '##-########'    },
])
